<?php
$quote = Mage::getSingleton('checkout/cart')->getQuote();
$paylike_helper = Mage::helper('paylike_payment');
$grand_total = $this->helper('checkout/cart')->getQuote()->getGrandTotal();
$currency_code = Mage::app()->getStore()->getCurrentCurrencyCode();
$paylike        = Mage::getModel( 'paylike_payment/paylike' );
$client         = $paylike->getClient(); // load vendor
$currencies     = new Paylike_Data_Currencies();
$email = $quote->getBillingAddress()->getEmail();
$name = $quote->getBillingAddress()->getName();
if (!$email) {
    $email = $quote->getCustomerEmail();
}
if (!$name) {
    $name = $quote->getCustomerName();
} ?>
<script class="text/javascript">
    paylikeVAR.tax = '<?php echo Mage::helper('checkout')->getQuote()->getShippingAddress()->getData('tax_amount'); ?>';
    paylikeVAR.amountpaylike = <?php echo $currencies->ceil($grand_total, $currency_code) ?>;
    paylikeVAR.telephone = '<?php echo $paylike_helper->getTelephone(); ?>';
    paylikeVAR.address = '<?php echo $paylike_helper->getAddress(); ?>';
    paylikeVAR.email = '<?php echo $email; ?>';
    paylikeVAR.name = '<?php echo $name; ?>';
    window.paylikeSelectedMethodOfShipping = '<?php echo Mage::helper('checkout')->getQuote()->getShippingAddress()->getShippingMethod(); ?>';
</script>