<?php
$quote = Mage::getSingleton('checkout/cart')->getQuote();
$email = $quote->getBillingAddress()->getEmail();
$name = $quote->getBillingAddress()->getName();
if (!$email) {
    $email = $quote->getCustomerEmail();
}
if (!$name) {
    $name = $quote->getCustomerName();
}
if (Mage::getStoreConfig('payment/paymentgateway/status')) {
    ?>
    <style>
        .paylike-logo {width: 40px; padding-right: 10px;}
        label[for="p_method_paymentgateway"] span{float:left; margin-right:10px; margin-top: 6px;}
        label[for="p_method_paymentgateway"] p{clear:both;}
        label[for="p_method_paymentgateway"] span ~ img{margin-top:5px;}
    </style>
    <script type="text/javascript">
        document.getElementById('p_method_paymentgateway').checked = false;

        var payment_method_desc = '<?php echo Mage::helper('paymentgateway')->getPaymentMethodDescription(); ?>';
        var payment_method_caredit_card_logos = '<?php echo Mage::helper('paymentgateway')->getCreditCardLogos(true); ?>';
        var payment_method_title = jQuery('#p_method_paymentgateway').parents('dt').find('label[for="p_method_paymentgateway"]').text();
        var html = '<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/paylike/logo.png" alt="Paylike" title="Paylike" class="v-middle paylike-logo" />';
        html += '<span>' + payment_method_title + '</span>';
        payment_method_caredit_card_logos = jQuery.parseJSON(payment_method_caredit_card_logos);
        jQuery.each(payment_method_caredit_card_logos, function(index, item) {
            html += '<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN); ?>frontend/paylike/logos/' + item + '" alt="' + item + '" title="' + item + '" class="v-middle paylike-logo" style="height:26px;" />';
        });
        html += '<p>' + payment_method_desc + '</p>';
        jQuery('#p_method_paymentgateway').parents('dt').find('label[for="p_method_paymentgateway"]').html(html);

        jQuery("button").click(function () {
            var attr = jQuery(this).attr('onclick');
            if (typeof attr !== typeof undefined && attr !== false && attr == 'payment.save()') {
                if (jQuery("#p_method_paymentgateway").is(":checked")) {
                    continueBtnClickHandler();
                }
            }
        });

        jQuery("input:radio").change(function () {
            if (!jQuery("#p_method_paymentgateway").is(":checked")) {
                if (jQuery('#errorMessage').length > 0) {
                    jQuery('#errorMessage').remove();
                }
            }
        });

        function showError(message) {
            if (jQuery('#errorMessage').length > 0) {
                jQuery('#errorMessage').remove();
            }
            var html = '<div id="errorMessage" style="color: #ff0000; font-size: 13px; font-weight: normal;">' + message + '</div>';
            jQuery('#p_method_paymentgateway').parent('dt').append(html);
        }

        var payment_mode = '<?php echo Mage::helper('paymentgateway')->getPaymentMode(); ?>';
        var locale = '<?php echo Mage::app()->getLocale()->getLocaleCode();?>';
        var popupTitle = '<?php echo Mage::helper('paymentgateway')->getPopupTitle(); ?>';
        var popupDescription = '<?php echo Mage::helper('paymentgateway')->getPopupDescription(); ?>';
        var currency = '<?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?>';
        var publicKey = '<?php echo Mage::helper('paymentgateway')->getPublicKey(); ?>';
        var amount = '<?php echo $this->helper('checkout/cart')->getQuote()->getGrandTotal();?>';
        var quoteId = '<?php echo $this->helper('checkout/cart')->getQuote()->getId();?>';
        var products = '<?php echo Mage::helper('paymentgateway')->getProducts(true); ?>';
        var telephone = '<?php echo Mage::helper('paymentgateway')->getTelephone(); ?>';
        var address = '<?php echo Mage::helper('paymentgateway')->getAddress(); ?>';
        var email = '<?php echo $email;?>';
        var name = '<?php echo $name;?>';
        var tax = '<?php echo Mage::helper('checkout')->getQuote()->getShippingAddress()->getData('tax_amount'); ?>';
        var shipping = '<?php echo $this->helper('checkout/cart')->getQuote()->getShippingAddress()->getShippingAmount(); ?>';
        var customerIp = '<?php echo Mage::helper('core/http')->getRemoteAddr(); ?>';
        var platform_version = '<?php echo Mage::getVersion(); ?>';
        var version = '<?php echo Mage::getConfig()->getNode()->modules->Paylike_Paymentgateway->version; ?>';

        //document.querySelector('#p_method_paymentgateway').addEventListener('click', pay);
        document.querySelector('#p_method_paymentgateway').addEventListener('click', paylikePaymentgatewaySelectHandler);

        function paylikePaymentgatewaySelectHandler() {
            //document.getElementById("transaction-id").value = "5910238566b6776329301fb9";
            document.getElementById("transaction-id").removeAttribute("disabled");
            document.getElementById("transaction-id").value = String(Math.floor((Math.random() * 1000000000000) + 1));
        }

        function continueBtnClickHandler() {
            if (document.querySelector('.btn-checkout') != null) {
                document.querySelector('.btn-checkout').remove();
            }

            var checkoutFlag = setInterval(function () {
                if (document.querySelector('.btn-checkout') != null) {
                    document.querySelector('.btn-checkout').removeAttribute('onclick');
                    document.querySelector('.btn-checkout').addEventListener('click', pay);
                    clearInterval(checkoutFlag);
                }
            }, 500);
        }

        function pay(e) {
            if (publicKey) {
                var paylike = Paylike(publicKey);
                document.getElementById("transaction-id").removeAttribute("disabled");
                var amountpaylike = amount * 100;
                paylike.popup({
                    currency: currency,
                    amount: amountpaylike,
                    title: popupTitle,
                    description: popupDescription,
                    custom: {
                        quoteId: quoteId,
                        products: jQuery.parseJSON(products),
                        email: email,
                        name: name,
                        telephone: telephone,
                        address: address,
                        customerIp: customerIp,
                        platform_version: platform_version,
                        ecommerce: 'magento',
                        version: version
                    },
                    locale: locale
                }, function (err, res) {
                    if (err) {
                        if (err == 'closed') {
                            //document.getElementById('p_method_paymentgateway').checked = false;
                        }
                        return console.log(err);
                    }
                    document.getElementById("transaction-id").value = res.transaction.id.toString();

                    //payment.save();
                    review.save();
                });
            } else {
                var message = '';
                if (payment_mode == 'test') {
                    message = 'Paylike Test Public key not set';
                } else {
                    message = 'Paylike Live Public key not set';
                }
                showError(message);
            }
        }

    </script>
    <input type="hidden" id="transaction-id" name="payment[paylike_transaction_id]"/>
    <?php
}
